### ISSUE TITLE
Create quick guide for speakers 

### ISSUE THREAD

**Issue by courtneycl** [maptime/dc#7]
It would be helpful to provide a quick guide for upcoming speakers with information on Maptime and things to consider as they are preparing their presentation. 

We can copy it from other chapters and add it to our wiki.
http://maptimesea.github.io/guidelines/
https://docs.google.com/document/d/1FkwY1C1xr8U1Nx5TKmBrFMeaLAeEhL6CqlfM0lY6-9I/edit

**Comment by geobrando** [comment]
:+1:

**Comment by briandaviddavidson** [comment]
How is this coming along? Anything I can do to help?
